
export const storeSkinItems = [
  {
    id: "alagoas",
    imageKey: "alagoasSkin",
    skinName: "Iracema",
    skinZone: "Alagoas",
    flagZoneKey: "bandeiraAlagoas",
    skinPrice: "2000",
  },
  {
    id: "bahia",
    imageKey: "bahiaSkin",
    skinName: "Marinalva",
    skinZone: "Bahia",
    flagZoneKey: "bandeiraBahia",
    skinPrice: "2000",
  },
  {
    id: "ceara",
    imageKey: "cearaSkin",
    skinName: "Raimundinho",
    skinZone: "Ceará",
    flagZoneKey: "bandeiraCeara",
    skinPrice: "2000",
  },
  {
    id: "maranhao",
    imageKey: "maranhaoSkin",
    skinName: "Zeca",
    skinZone: "Maranhão",
    flagZoneKey: "bandeiraMaranhao",
    skinPrice: "2000",
  },
  {
    id: "paraiba",
    imageKey: "paraibaSkin",
    skinName: "Bené",
    skinZone: "Paraíba",
    flagZoneKey: "bandeiraParaiba",
    skinPrice: "2000",
  },
  {
    id: "pernambuco",
    imageKey: "pernambucoSkin",
    skinName: "Rita",
    skinZone: "Pernambuco",
    flagZoneKey: "bandeiraPernambuco",
    skinPrice: "2000",
  },
  {
    id: "piaui",
    imageKey: "piauiSkin",
    skinName: "Inácio",
    skinZone: "Piaui",
    skinPrice: "2000",
    flagZoneKey: "bandeiraPiaui",
  },
  {
    id: "rn",
    imageKey: "rnSkin",
    skinName: "Irandir",
    skinZone: "Rio Grande Do Norte",
    flagZoneKey: "bandeiraRn",
    skinPrice: "2000",
  },
  {
    id: "sergipe",
    imageKey: "sergipeSkin",
    skinName: "Zazá",
    skinZone: "Sergipe",
    flagZoneKey: "bandeiraSergipe",
    skinPrice: "2000",
  },
] as const;
